# Generated by Django 5.2.15 on 2026-06-11 21:52

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_type', models.CharField(choices=[('transfer', 'Transfer'), ('hourly', 'Hourly')], default='transfer', max_length=20)),
                ('service', models.CharField(blank=True, max_length=120)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('base_rate', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hourly_rate', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10)),
                ('min_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('la_reservation_id', models.CharField(blank=True, max_length=64)),
                ('trip_status', models.CharField(blank=True, choices=[('unassigned', 'Unassigned'), ('farm_out_unassigned', 'Farm-out Unassigned'), ('pending', 'Pending'), ('offered', 'Offered'), ('assigned', 'Assigned'), ('dispatched', 'Dispatched - Driver Assigned'), ('on_the_way', 'On The Way'), ('circling', 'Circling'), ('arrived', 'Arrived'), ('customer_in_car', 'Customer In Car'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('cancelled_by_affiliate', 'Cancelled by Affiliate'), ('late_cancel', 'Late Cancel'), ('no_show', 'No Show'), ('covid_cancellation', 'COVID-19 Cancellation'), ('offered_to_affiliate', 'Offered to Affiliate'), ('affiliate_assigned', 'Affiliate is Assigned'), ('dispatched_non_la', 'Dispatched - Driver Assigned NON LA')], default='', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='leads.lead')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.vehicle')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='reservations.reservation')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='TripStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('farm_out_unassigned', 'Farm-out Unassigned'), ('pending', 'Pending'), ('offered', 'Offered'), ('assigned', 'Assigned'), ('dispatched', 'Dispatched - Driver Assigned'), ('on_the_way', 'On The Way'), ('circling', 'Circling'), ('arrived', 'Arrived'), ('customer_in_car', 'Customer In Car'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('cancelled_by_affiliate', 'Cancelled by Affiliate'), ('late_cancel', 'Late Cancel'), ('no_show', 'No Show'), ('covid_cancellation', 'COVID-19 Cancellation'), ('offered_to_affiliate', 'Offered to Affiliate'), ('affiliate_assigned', 'Affiliate is Assigned'), ('dispatched_non_la', 'Dispatched - Driver Assigned NON LA')], max_length=32)),
                ('source', models.CharField(choices=[('limoanywhere', 'LimoAnywhere'), ('manual', 'Manual')], default='limoanywhere', max_length=20)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
