# Generated by Django 5.2.15 on 2026-06-14 14:21

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='recognized_amount',
            field=apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='recognized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='revenue_status',
            field=models.CharField(choices=[('deferred', 'Deferred'), ('recognized', 'Recognized'), ('reversed', 'Reversed')], default='deferred', max_length=20),
        ),
    ]
