# Generated by Django 5.2.15 on 2026-07-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_seed_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='la_confirmation',
            field=models.CharField(blank=True, max_length=64, verbose_name='LA confirmation #'),
        ),
        migrations.AddField(
            model_name='stop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
