# Generated by Django 5.2.15 on 2026-07-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_la_confirmation_stop_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='stop',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
