# Generated by Django 5.2.15 on 2026-07-24 11:41

from datetime import datetime, timedelta
from decimal import Decimal

import apps.core.fields
from django.db import migrations, models


def backfill_pricing(apps, schema_editor):
    """Preserve every existing line_total: hourly keeps rate/hours, transfer becomes rate×1."""
    Reservation = apps.get_model("reservations", "Reservation")
    for r in Reservation.objects.all():
        if r.trip_type == "hourly":
            r.rate = r.hourly_rate  # hours, min_hours unchanged
        else:  # transfer -> flat becomes rate × 1
            r.rate = r.base_rate
            r.hours = Decimal("1")
            r.min_hours = Decimal("0")
        if r.pickup_date and r.pickup_time:
            billed = max(Decimal(r.hours or 0), Decimal(r.min_hours or 0))
            end = datetime.combine(r.pickup_date, r.pickup_time) + timedelta(hours=float(billed))
            r.dropoff_date, r.dropoff_time = end.date(), end.time()
        r.save(update_fields=["rate", "hours", "min_hours", "dropoff_date", "dropoff_time"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_stop_name_stop_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='discount_flat',
            field=apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='reservation',
            name='dropoff_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='dropoff_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gratuity_flat',
            field=apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gratuity_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rate',
            field=apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(backfill_pricing, noop),
    ]
