# Generated by Django 5.2.15 on 2026-07-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservation_discount_flat_reservation_discount_pct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='base_rate',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='hourly_rate',
        ),
    ]
