# Generated by Django 5.2.17 on 2026-08-29 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_airline'),
        ('reservations', '0008_min_applied_rows_become_no_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addresses.airline'),
        ),
        migrations.AddField(
            model_name='stop',
            name='airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='addresses.airport'),
        ),
        migrations.AddField(
            model_name='stop',
            name='flight_number',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
