# Generated by Django 5.2.17 on 2026-08-29 22:17

import django.db.models.deletion
from django.db import migrations, models

from apps.reservations.migrations import backfill_flight_direction


def backfill(apps, schema_editor):
    backfill_flight_direction(
        Reservation=apps.get_model("reservations", "Reservation"),
        Stop=apps.get_model("reservations", "Stop"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_airport_timezone'),
        ('reservations', '0009_stop_flight_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='flight_direction',
            field=models.CharField(blank=True, choices=[('arrival', 'Arriving'), ('departure', 'Departing')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_number', models.CharField(max_length=6)),
                ('flight_date', models.DateField()),
                ('direction', models.CharField(choices=[('arrival', 'Arriving'), ('departure', 'Departing')], max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('landed', 'Landed'), ('cancelled', 'Cancelled'), ('diverted', 'Diverted'), ('incident', 'Incident'), ('not_found', 'Not found'), ('unavailable', 'Unavailable')], default='scheduled', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_at', models.DateTimeField(blank=True, null=True)),
                ('actual_at', models.DateTimeField(blank=True, null=True)),
                ('delay_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('terminal', models.CharField(blank=True, max_length=16)),
                ('gate', models.CharField(blank=True, max_length=16)),
                ('other_airport_iata', models.CharField(blank=True, max_length=4)),
                ('other_airport_name', models.CharField(blank=True, max_length=120)),
                ('operated_by_iata', models.CharField(blank=True, max_length=3)),
                ('operated_by_name', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, choices=[('flightsFuture', 'Future schedule'), ('flights', 'Live')], default='', max_length=14)),
                ('checked_at', models.DateTimeField()),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addresses.airline')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addresses.airport')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stop',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stops', to='reservations.flight'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.UniqueConstraint(fields=('airline', 'flight_number', 'flight_date', 'airport', 'direction'), name='uniq_flight_lookup'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
