# Generated by Django 5.2.17 on 2026-08-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_service_type_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='source_leg_id',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
