# Generated by Django 5.2.17 on 2026-08-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_reservation_source_leg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pickup_timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
