# Generated by Django 5.2.17 on 2026-09-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_reservation_pickup_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='group_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
