# Generated by Django 5.2.17 on 2026-09-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_reservation_group_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
