# Generated by Django 5.2.17 on 2026-09-06 03:46

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_reservation_customer_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='affiliate_cost',
            field=apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cost_ratio_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
