# Generated by Django 5.2.17 on 2026-09-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_reservation_affiliate_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('default_cost_ratio_pct', models.DecimalField(decimal_places=2, default=65, max_digits=5)),
            ],
            options={
                'verbose_name': 'Pricing settings',
                'verbose_name_plural': 'Pricing settings',
            },
        ),
    ]
