# Generated by Django 5.2.17 on 2026-09-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_pricingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='dropoff_estimated',
            field=models.BooleanField(default=False),
        ),
    ]
