# Generated by Django 5.2.17 on 2026-09-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_trip_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreview',
            name='affiliate_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tripreview',
            name='driver_overtime_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
