# Generated by Django 5.2.17 on 2026-09-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_trip_review_driver_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripreview',
            name='affiliate_rate',
        ),
        migrations.RemoveField(
            model_name='tripreview',
            name='driver_overtime_minutes',
        ),
        migrations.AddField(
            model_name='tripreview',
            name='affiliate_overtime_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tripreview',
            name='affiliate_overtime_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tripreview',
            name='driver_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tripreview',
            name='driver_pay_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
