# Generated by Django 5.2.17 on 2026-09-26 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskConfig',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, help_text='Turn task generation and escalation off without losing settings.')),
                ('overdue_grace_hours', models.PositiveIntegerField(default=24, help_text='How long a task can sit overdue before it escalates to the department owner and admins.')),
                ('digest_emails', models.TextField(blank=True, help_text='Who gets the daily overdue-task digest. One per line or comma-separated. Blank falls back to the company email.')),
                ('accounting_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Accounting owner')),
                ('affiliate_mgmt_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Affiliate Management owner')),
                ('customer_service_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Customer Service owner')),
                ('operations_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Operations owner')),
                ('sales_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Sales owner')),
            ],
            options={
                'verbose_name': 'task configuration',
            },
        ),
    ]
