# Generated by Django 5.2.17 on 2026-09-26 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_vehicle_type_group_transport'),
        ('reservations', '0019_backfill_cost_ratio'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=40)),
                ('department', models.CharField(choices=[('sales', 'Sales'), ('operations', 'Operations'), ('affiliate_mgmt', 'Affiliate Management'), ('customer_service', 'Customer Service'), ('accounting', 'Accounting')], max_length=32)),
                ('status', models.CharField(choices=[('scheduled', 'Not open yet'), ('open', 'Open'), ('done', 'Done'), ('skipped', 'Skipped'), ('not_applicable', 'Not applicable')], default='open', max_length=20)),
                ('opens_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_tier', models.PositiveSmallIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.lead')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='reservations.reservation')),
            ],
            options={
                'ordering': ['due_at', 'pk'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'due_at'], name='tasks_task_status_1f2475_idx'), models.Index(fields=['assignee', 'status'], name='tasks_task_assigne_7928f6_idx')],
                'constraints': [models.UniqueConstraint(fields=('lead', 'reservation', 'kind'), name='one_task_per_kind')],
            },
        ),
    ]
