# Generated by Django 5.2.17 on 2026-09-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfig',
            name='digest_sent_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
