# Generated by Django 5.2.17 on 2026-09-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskconfig_digest_sent_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfig',
            name='post_trip_grace_hours',
            field=models.PositiveIntegerField(default=2, help_text="How long after a trip's scheduled end, with no Done status, before its post-trip review opens anyway."),
        ),
    ]
