# Generated by Django 5.2.17 on 2026-09-27 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskconfig_post_trip_grace_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfig',
            name='overtime_grace_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Minutes over the billed hours before any overtime is suggested. Placeholder until the client confirms.'),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='overtime_increment_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Suggested overtime rounds up to this many minutes. Placeholder until the client confirms.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
