# Generated by Django 5.2.17 on 2026-09-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskconfig_overtime_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfig',
            name='future_booking_offset_days',
            field=models.PositiveIntegerField(default=330, help_text="Days after an order's last trip that Sales follows up about booking again (330 is about a wedding's first anniversary)."),
        ),
    ]
