# Generated by Django 5.2.17 on 2026-09-27 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_customer_feedback'),
        ('reservations', '0020_trip_review'),
        ('tasks', '0006_taskconfig_future_booking_offset_days'),
        ('vendors', '0006_vendordocument_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='vendors.vendorinsurance'),
        ),
        migrations.AddField(
            model_name='task',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.lead'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('insurance', 'kind'), name='one_task_per_policy'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lead__isnull', False), ('vendor__isnull', True)), models.Q(('lead__isnull', True), ('vendor__isnull', False)), _connector='OR'), name='task_order_or_vendor'),
        ),
    ]
