# Generated by Django 5.2.15 on 2026-06-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_payments',
            field=models.BooleanField(default=False, help_text='May run money actions (refunds, mark-paid, retry charges).', verbose_name='can manage payments'),
        ),
    ]
