# Generated by Django 5.2.15 on 2026-06-12 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=4)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('apple', 'Apple')], default='sms', max_length=20)),
                ('body', models.TextField(blank=True)),
                ('podium_conversation_uid', models.CharField(blank=True, max_length=64)),
                ('podium_message_uid', models.CharField(blank=True, max_length=64)),
                ('delivery_status', models.CharField(blank=True, choices=[('sent', 'Sent'), ('received', 'Received'), ('failed', 'Failed')], max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leads.lead')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('podium_review_invite_uid', models.CharField(blank=True, max_length=64)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('link_clicked', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('body', models.TextField(blank=True)),
                ('review_site', models.CharField(blank=True, max_length=80)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='contacts.contact')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TouchPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('greeting', 'Greeting'), ('quote_followup', 'Quote follow-up'), ('pretrip_reminder', 'Pre-trip reminder'), ('review_request', 'Review request')], max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('skipped', 'Skipped')], default='scheduled', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('podium_message_uid', models.CharField(blank=True, max_length=64)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touchpoints', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
