# Generated by Django 5.2.15 on 2026-07-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touchpoint',
            name='error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='touchpoint',
            name='kind',
            field=models.CharField(choices=[('tp1_welcome', 'Welcome message'), ('tp2_lead_followup', 'Lead follow-up'), ('tp3_quote_sent_sms', 'Quote sent (SMS)'), ('tp4_viewed_sms', 'Quote viewed (SMS)'), ('tp5_viewed_email', 'Quote viewed (Email)'), ('tp6_quote_followup', 'Quote follow-up'), ('tp7_expiring', 'Quote expiring'), ('tp8_expired', 'Quote expired'), ('review_request', 'Review request')], max_length=30),
        ),
        migrations.AlterField(
            model_name='touchpoint',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='scheduled', max_length=20),
        ),
    ]
