# Generated by Django 5.2.15 on 2026-07-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_read_at_touchpoint_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='podium_sender_uid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
