# Generated by Django 5.2.15 on 2026-07-28 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_backfill_message_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='lead',
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation'),
        ),
    ]
