# Generated by Django 5.2.17 on 2026-08-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_remove_message_lead_alter_message_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touchpoint',
            name='kind',
            field=models.CharField(choices=[('tp1_welcome', 'Welcome message'), ('tp2_lead_followup', 'Lead follow-up'), ('tp3_quote_sent_sms', 'Quote sent (SMS)'), ('tp4_viewed_sms', 'Quote viewed (SMS)'), ('tp5_viewed_email', 'Quote viewed (Email)'), ('tp6_quote_followup', 'Quote follow-up'), ('tp7_expiring', 'Quote expiring'), ('tp8_expired', 'Quote expired'), ('review_request', 'Review request'), ('payment_reminder', 'Payment reminder')], max_length=30),
        ),
    ]
