# Generated by Django 5.2.17 on 2026-09-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_touchpoint_reservation_alter_touchpoint_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, help_text='Master switch — turn every lifecycle message off at once.')),
                ('wedding_final_details_enabled', models.BooleanField(default=True, help_text='APC-18 · T-7d wedding: request day-of contact + wedding name.')),
                ('trip_confirm_customer_enabled', models.BooleanField(default=True, help_text='APC-19 · T-72h customer trip confirmation + acknowledgement.')),
                ('trip_confirm_affiliate_enabled', models.BooleanField(default=True, help_text='APC-20 · T-48h affiliate trip confirmation + acknowledgement.')),
                ('driver_released_enabled', models.BooleanField(default=True, help_text='APC-21 · release driver + vehicle details to the customer.')),
                ('status_dispatched_enabled', models.BooleanField(default=False, help_text='APC-22 · Dispatched.')),
                ('status_on_the_way_enabled', models.BooleanField(default=False, help_text='APC-22 · On The Way.')),
                ('status_arrived_enabled', models.BooleanField(default=False, help_text='APC-22 · Arrived.')),
            ],
            options={
                'verbose_name': 'notification configuration',
            },
        ),
    ]
