# Generated by Django 5.2.17 on 2026-09-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_notificationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationconfig',
            name='trip_confirm_customer_enabled',
            field=models.BooleanField(default=True, help_text='APC-19 · customer trip confirmation + acknowledgement (T-72h, repeated T-48h).'),
        ),
        migrations.AlterField(
            model_name='touchpoint',
            name='kind',
            field=models.CharField(choices=[('tp1_welcome', 'Welcome message'), ('tp2_lead_followup', 'Lead follow-up'), ('tp3_quote_sent_sms', 'Quote sent (SMS)'), ('tp4_viewed_sms', 'Quote viewed (SMS)'), ('tp5_viewed_email', 'Quote viewed (Email)'), ('tp6_quote_followup', 'Quote follow-up'), ('tp7_expiring', 'Quote expiring'), ('tp8_expired', 'Quote expired'), ('review_request', 'Review request'), ('payment_reminder', 'Payment reminder'), ('wed_final_details', 'Wedding: final day-of details (T-7d)'), ('trip_confirm_customer', 'Customer trip confirmation (T-72h)'), ('trip_confirm_customer_2', 'Customer trip confirmation — second notice (T-48h)'), ('trip_confirm_affiliate', 'Affiliate trip confirmation (T-48h)'), ('driver_released', 'Driver details released to customer'), ('status_dispatched', 'Trip status: Dispatched'), ('status_on_the_way', 'Trip status: On The Way'), ('status_arrived', 'Trip status: Arrived')], max_length=30),
        ),
    ]
