# Generated by Django 5.2.17 on 2026-09-20 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0013_contact_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qbo_customer_id', models.CharField(blank=True, max_length=64)),
                ('qbo_sync_state', models.CharField(choices=[('not_synced', 'Not synced'), ('synced', 'Synced'), ('error', 'Not synced')], default='not_synced', max_length=20)),
                ('qbo_sync_error', models.CharField(blank=True, max_length=255)),
                ('qbo_synced_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('terms', models.CharField(choices=[('due_on_receipt', 'Due on receipt'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45')], default='net_30', max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_accounts', to='contacts.contact')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qbo_customer_id', models.CharField(blank=True, max_length=64)),
                ('qbo_sync_state', models.CharField(choices=[('not_synced', 'Not synced'), ('synced', 'Synced'), ('error', 'Not synced')], default='not_synced', max_length=20)),
                ('qbo_sync_error', models.CharField(blank=True, max_length=255)),
                ('qbo_synced_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('invoice_email', models.EmailField(blank=True, max_length=254)),
                ('terms', models.CharField(blank=True, choices=[('due_on_receipt', 'Due on receipt'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45')], max_length=20)),
                ('po_required', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='billing.billingaccount')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='billingaccount',
            constraint=models.UniqueConstraint(fields=('contact',), name='uniq_billing_account_per_contact'),
        ),
        migrations.AddConstraint(
            model_name='accountgroup',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='uniq_group_name_per_account'),
        ),
    ]
