# Generated by Django 5.2.15 on 2026-06-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='podium_contact_uid',
            field=models.CharField(blank=True, max_length=64, verbose_name='Podium contact UID'),
        ),
    ]
