# Generated by Django 5.2.15 on 2026-07-24 03:35

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_backfill_phone_e164'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('billing_contact', models.ForeignKey(blank=True, help_text="The person billed for this company's bookings.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_companies', to='contacts.contact')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_company_name_ci')],
            },
        ),
    ]
