# Generated by Django 5.2.15 on 2026-07-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='company',
            new_name='company_legacy',
        ),
    ]
