# Generated by Django 5.2.15 on 2026-07-24 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_company_backfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company_legacy',
        ),
    ]
