# Generated by Django 5.2.15 on 2026-07-24 03:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_email_backfill'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_contact_email_ci'),
        ),
    ]
