# Generated by Django 5.2.15 on 2026-07-24 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_email_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
    ]
