# Generated by Django 5.2.15 on 2026-07-24 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('contacts', '0012_contact_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='addresses.address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='billing_same_as_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='primary_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='addresses.address'),
        ),
    ]
