# Generated by Django 5.2.17 on 2026-09-26 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0013_contact_addresses"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32)),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("work", "Work"),
                            ("home", "Home"),
                            ("other", "Other"),
                        ],
                        default="mobile",
                        max_length=10,
                    ),
                ),
                (
                    "texting",
                    models.BooleanField(
                        default=False, help_text="The number Podium texts. One per contact."
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["-texting", "created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("contact", "number"), name="uniq_contact_phone")
                ],
            },
        ),
    ]
