# Generated by Django 5.2.15 on 2026-07-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_zapevent_result_lacustomer_laevent'),
        ('messaging', '0006_backfill_message_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podiumevent',
            name='lead',
        ),
        migrations.AddField(
            model_name='podiumevent',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podium_events', to='messaging.conversation'),
        ),
    ]
