# Generated by Django 5.2.15 on 2026-08-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_remove_podiumevent_lead_podiumevent_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='podiumevent',
            name='event_uid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
