# Generated by Django 5.2.17 on 2026-08-31 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_backfill_podium_event_uid'),
        ('leads', '0009_lead_intake_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendlyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('invitee.created', 'Invitee created'), ('invitee.canceled', 'Invitee canceled')], max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendly_events', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
