# Generated by Django 5.2.15 on 2026-07-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ourairports_id', models.PositiveIntegerField(unique=True)),
                ('ident', models.CharField(db_index=True, max_length=8, unique=True)),
                ('iata', models.CharField(blank=True, db_index=True, max_length=8)),
                ('icao', models.CharField(blank=True, db_index=True, max_length=8)),
                ('size', models.CharField(choices=[('large_airport', 'Large'), ('medium_airport', 'Medium')], max_length=20)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('city', models.CharField(db_index=True, max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(default='US', max_length=2)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('elevation_ft', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('locationiq_place_id', models.CharField(blank=True, max_length=64)),
                ('line1', models.CharField(blank=True, max_length=200)),
                ('postal', models.CharField(blank=True, max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=300)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
