# Generated by Django 5.2.17 on 2026-08-29 03:25

from django.db import migrations, models

from apps.addresses.loaders import load_airlines


def seed(apps, schema_editor):
    load_airlines(apps.get_model("addresses", "Airline"))


def unseed(apps, schema_editor):
    apps.get_model("addresses", "Airline").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_seed_airports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iata', models.CharField(max_length=3, unique=True)),
                ('icao', models.CharField(blank=True, max_length=4)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed, unseed),
    ]
