# Generated by Django 5.2.17 on 2026-09-07 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0010_seed_venues_dmv'),
        ('leads', '0012_vehicle_type_group_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='max_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capped_venues', to='leads.vehicletype'),
        ),
    ]
