# Generated by Django 5.2.17 on 2026-08-20 20:04

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0007_remove_reservation_base_rate_and_more'),
        ('vendors', '0004_remove_vendor_address_line1_remove_vendor_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='offered', max_length=20)),
                ('channel', models.CharField(choices=[('manual', 'Manual'), ('gnet', 'GNet')], default='manual', max_length=20)),
                ('payout', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('offered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reservations.reservation')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['reservation', 'status'], name='dispatch_as_reserva_8913d2_idx')],
            },
        ),
    ]
