# Generated by Django 5.2.17 on 2026-08-25 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='gnet_transaction_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='GnetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('send_trip', 'Send trip'), ('cancel_trip', 'Cancel trip'), ('callback', 'Callback')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error'), ('preview', 'Preview (not sent)')], default='pending', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gnet_events', to='dispatch.assignment')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
