# Generated by Django 5.2.17 on 2026-08-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_assignment_gnet_transaction_id_gnetevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='gnet_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
