# Generated by Django 5.2.17 on 2026-08-30 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_alter_assignment_gnet_transaction_id'),
        ('fleet', '0003_seed_renewal_types'),
        ('reservations', '0009_stop_flight_info'),
        ('vendors', '0005_vendor_gnet_grid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='fleet.vehicle'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='vendors.vendor'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('driver__isnull', True), ('vendor__isnull', False)), models.Q(('driver__isnull', False), ('vendor__isnull', True)), _connector='OR'), name='assignment_one_provider'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('vehicle__isnull', True), ('driver__isnull', False), _connector='OR'), name='assignment_vehicle_needs_driver'),
        ),
    ]
