# Generated by Django 5.2.17 on 2026-09-03 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_assignment_in_house'),
        ('reservations', '0014_reservation_group_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchAlertConfig',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, help_text='Turn the whole monitor off without losing your thresholds.')),
                ('unassigned_warn_hours', models.PositiveIntegerField(default=24)),
                ('unassigned_critical_hours', models.PositiveIntegerField(default=4)),
                ('otw_warn_minutes', models.PositiveIntegerField(default=45)),
                ('otw_critical_minutes', models.PositiveIntegerField(default=15)),
                ('arrived_warn_minutes', models.PositiveIntegerField(default=15)),
                ('arrived_critical_minutes', models.PositiveIntegerField(default=45)),
                ('alert_emails', models.TextField(blank=True, help_text='Who gets the exception digest email. One per line or comma-separated. Blank falls back to the company email.')),
                ('critical_sms', models.TextField(blank=True, help_text='Phone numbers texted for critical-tier exceptions only. One per line or comma-separated. Blank means no SMS.')),
            ],
            options={
                'verbose_name': 'dispatch alert configuration',
            },
        ),
        migrations.CreateModel(
            name='DispatchException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('unassigned', 'No coverage'), ('not_otw', 'Not en route'), ('not_arrived', 'Not arrived')], max_length=20)),
                ('tier', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=12)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notified_tier', models.CharField(blank=True, default='', max_length=12)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_exceptions', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('reservation', 'kind'), name='one_exception_per_kind_per_trip')],
            },
        ),
    ]
