# Generated by Django 5.2.17 on 2026-09-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_dispatchalertconfig_dispatchexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='affiliate_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='driver_cell',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='assignment',
            name='driver_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assignment',
            name='vehicle_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assignment',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
