# Generated by Django 5.2.17 on 2026-09-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_assignment_affiliate_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchalertconfig',
            name='driver_info_critical_hours',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='dispatchalertconfig',
            name='driver_info_warn_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='dispatchexception',
            name='kind',
            field=models.CharField(choices=[('unassigned', 'No coverage'), ('not_otw', 'Not en route'), ('not_arrived', 'Not arrived'), ('no_driver_info', 'Driver info missing')], max_length=20),
        ),
    ]
