# Generated by Django 5.2.17 on 2026-09-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_dispatchalertconfig_affiliate_unacked_warn_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='driver_info_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
