# Generated by Django 5.2.15 on 2026-06-11 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('klass', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van'), ('mini_coach', 'Mini Coach'), ('coach', 'Motor Coach'), ('limo', 'Limousine')], default='sedan', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('booked', 'Booked'), ('lost', 'Lost')], default='new', max_length=20)),
                ('channel', models.CharField(choices=[('website', 'Website'), ('wedding_pro', 'Wedding Pro'), ('phone', 'Phone'), ('api', 'API')], default='website', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('lost_reason', models.CharField(blank=True, max_length=255)),
                ('has_alert', models.BooleanField(default=False)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='contacts.contact')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
