# Generated by Django 5.2.15 on 2026-07-19 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_podium_contact_uid'),
        ('leads', '0003_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='billing_contact',
            field=models.ForeignKey(blank=True, help_text='Leave blank when the booking contact is also billed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_leads', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='passenger_names',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='quote_last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='quote_view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
