# Generated by Django 5.2.15 on 2026-07-24 11:28

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_billing_contact_lead_passenger_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='promo_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='hourly_min_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='rate',
            field=apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='transfer_min_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
