# Generated by Django 5.2.15 on 2026-07-24 11:36

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_promo_code_vehicletype_hourly_min_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='hourly_min_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='rate',
            field=apps.core.fields.MoneyField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='transfer_min_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
