# Generated by Django 5.2.17 on 2026-08-30 05:04

import django.db.models.functions.text
from django.db import migrations, models

# The occasions the public booking widget already offered as hardcoded choices, so the
# catalog starts where the site left off. Everything after this is edited in Settings.
STARTER_CATALOG = [
    "Airport Transfer",
    "Corporate Travel",
    "Wedding Transportation",
    "Group / Shuttle Service",
    "Night Out",
    "Other",
]


def seed_service_types(apps, _schema_editor):
    ServiceType = apps.get_model("leads", "ServiceType")
    for order, name in enumerate(STARTER_CATALOG):
        ServiceType.objects.get_or_create(name=name, defaults={"sort_order": order})


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_transfer_min_hours_default_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_service_type_name_ci', violation_error_message='A service type with that name already exists.')],
            },
        ),
        migrations.RunPython(seed_service_types, migrations.RunPython.noop),
    ]
