# Generated by Django 5.2.17 on 2026-08-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='intake_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
