# Generated by Django 5.2.17 on 2026-09-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_intake_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='day_of_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='day_of_contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='wedding_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
