# Generated by Django 5.2.17 on 2026-09-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_day_of_contact_name_lead_day_of_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('engaged', 'Engaged'), ('booked', 'Booked'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
