# Generated by Django 5.2.17 on 2026-09-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_vehicle_type_group_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='accepted_terms_version',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
