# Generated by Django 5.2.17 on 2026-09-27 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_accepted_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField()),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='leads.lead')),
            ],
            options={
                'verbose_name_plural': 'customer feedback',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='customer_feedback_rating_1_to_5')],
            },
        ),
    ]
