# Generated by Django 5.2.17 on 2026-09-27 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_backfill_contact_phones'),
        ('leads', '0014_customer_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('couple', 'Couple'), ('lead_planner', 'Lead planner'), ('day_of_coordinator', 'Day-of coordinator'), ('assistant_coordinator', 'Assistant coordinator'), ('emergency', 'Emergency contact'), ('transportation', 'Transportation contact')], max_length=32)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_roles', to='contacts.contact')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='leads.lead')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('lead', 'contact', 'role'), name='one_role_per_lead_contact')],
            },
        ),
    ]
