# Generated by Django 5.2.17 on 2026-08-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(help_text='Slot start, UTC.', unique=True)),
                ('session_key', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
