# Generated by Django 5.2.15 on 2026-06-12 02:41

import apps.core.fields
import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit_pct', models.PositiveSmallIntegerField(default=apps.payments.models.default_deposit_pct)),
                ('quote_total', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_status', models.CharField(choices=[('unsent', 'Unsent'), ('requested', 'Requested'), ('paid', 'Paid')], default='unsent', max_length=20)),
                ('balance_status', models.CharField(choices=[('na', 'N/A'), ('scheduled', 'Scheduled'), ('paid', 'Paid'), ('failed', 'Failed')], default='na', max_length=20)),
                ('processor', models.CharField(default='stripe', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=64)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('fail_reason', models.CharField(blank=True, max_length=255)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('deposit', 'Deposit'), ('balance', 'Balance')], max_length=20)),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='payments.paymentplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
