# Generated by Django 5.2.15 on 2026-06-14 13:59

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('payments', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('deposit_captured', 'Deposit captured'), ('balance_captured', 'Balance captured'), ('revenue_recognized', 'Revenue recognized'), ('refund_issued', 'Refund issued'), ('deposit_forfeited', 'Deposit forfeited'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment')], max_length=32)),
                ('source', models.CharField(choices=[('stripe', 'Stripe'), ('system', 'System'), ('manual', 'Manual')], default='system', max_length=20)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('stripe_ref', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.charge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='leads.lead')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(choices=[('cash', 'Cash / Stripe Clearing'), ('customer_deposits', 'Customer Deposits'), ('accounts_receivable', 'Accounts Receivable'), ('recognized_revenue', 'Recognized Revenue'), ('cancellation_revenue', 'Cancellation Revenue'), ('refunds', 'Refunds'), ('processing_fees', 'Processing Fees'), ('vendor_cost', 'Vendor Cost'), ('vendor_payable', 'Vendor Payable')], max_length=32)),
                ('debit', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10)),
                ('credit', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payments.journalentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
