# Generated by Django 5.2.15 on 2026-06-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_journalentry_journalline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalline',
            options={'ordering': ['id']},
        ),
    ]
