# Generated by Django 5.2.15 on 2026-06-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_journalline_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='charge',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('balance', 'Balance'), ('refund', 'Refund')], max_length=20),
        ),
    ]
