# Generated by Django 5.2.17 on 2026-08-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_charge_stripe_refund_id_alter_charge_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='stripe_client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
