# Generated by Django 5.2.17 on 2026-09-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_charge_stripe_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='capture_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('succeeded', 'Succeeded'), ('released', 'Released'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='deposit_status',
            field=models.CharField(choices=[('unsent', 'Unsent'), ('requested', 'Requested'), ('authorized', 'Authorized'), ('paid', 'Paid')], default='unsent', max_length=20),
        ),
    ]
