# Generated by Django 5.2.17 on 2026-09-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_charge_authorized_at_charge_capture_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='charge',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
