# Generated by Django 5.2.17 on 2026-09-27 16:37

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_assignment_driver_info_at'),
        ('payments', '0007_charge_card_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('deposit_captured', 'Deposit captured'), ('balance_captured', 'Balance captured'), ('revenue_recognized', 'Revenue recognized'), ('refund_issued', 'Refund issued'), ('deposit_forfeited', 'Deposit forfeited'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment'), ('payable_accrued', 'Affiliate payable accrued'), ('payable_paid', 'Affiliate payable paid')], max_length=32),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.CharField(choices=[('cash', 'Cash / Stripe Clearing'), ('customer_deposits', 'Customer Deposits'), ('accounts_receivable', 'Accounts Receivable'), ('recognized_revenue', 'Recognized Revenue'), ('cancellation_revenue', 'Cancellation Revenue'), ('refunds', 'Refunds'), ('processing_fees', 'Processing Fees'), ('vendor_cost', 'Vendor Cost'), ('vendor_payable', 'Vendor Payable'), ('affiliate_disbursements', 'Affiliate disbursements')], max_length=32),
        ),
        migrations.CreateModel(
            name='AffiliatePayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('invoice_file', models.FileField(blank=True, upload_to='affiliate-invoices/')),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('approval_note', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_method', models.CharField(blank=True, choices=[('check', 'Check'), ('ach', 'ACH'), ('zelle', 'Zelle'), ('other', 'Other')], max_length=20)),
                ('paid_reference', models.CharField(blank=True, max_length=120)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payable', to='dispatch.assignment')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status'], name='payments_af_status_5908a7_idx')],
            },
        ),
    ]
