# Generated by Django 5.2.17 on 2026-09-27 16:48

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_affiliate_payable'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='overtime_amount',
            field=apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='charge',
            name='overtime_gratuity',
            field=apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='charge',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('balance', 'Balance'), ('refund', 'Refund'), ('final', 'Final bill')], max_length=20),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('deposit_captured', 'Deposit captured'), ('balance_captured', 'Balance captured'), ('revenue_recognized', 'Revenue recognized'), ('refund_issued', 'Refund issued'), ('deposit_forfeited', 'Deposit forfeited'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment'), ('overtime_captured', 'Overtime captured'), ('payable_accrued', 'Affiliate payable accrued'), ('payable_paid', 'Affiliate payable paid')], max_length=32),
        ),
    ]
