# Generated by Django 5.2.15 on 2026-07-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0004_lead_billing_contact_lead_passenger_names_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('service_area', models.CharField(blank=True, max_length=200)),
                ('location_name', models.CharField(blank=True, max_length=120, verbose_name='location label')),
                ('address_line1', models.CharField(blank=True, max_length=200, verbose_name='street address')),
                ('unit', models.CharField(blank=True, max_length=60, verbose_name='unit / suite')),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('usdot_number', models.CharField(blank=True, max_length=40, verbose_name='USDOT number')),
                ('notes', models.TextField(blank=True)),
                ('vehicle_types', models.ManyToManyField(blank=True, related_name='vendors', to='leads.vehicletype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
