# Generated by Django 5.2.15 on 2026-07-24 04:05

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendordocument_vendordriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurer', models.CharField(max_length=200)),
                ('policy_number', models.CharField(blank=True, max_length=80)),
                ('coverage_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('certificate', models.FileField(blank=True, upload_to='vendor-insurance/')),
                ('notes', models.TextField(blank=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-expiry_date'],
            },
        ),
    ]
