# Generated by Django 5.2.15 on 2026-07-24 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('vendors', '0003_vendorinsurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='unit',
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='addresses.address'),
        ),
    ]
