# Generated by Django 5.2.17 on 2026-08-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_remove_vendor_address_line1_remove_vendor_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='gnet_grid_id',
            field=models.CharField(blank=True, help_text="The affiliate's GNet id. Set this and trips farm out over GNet instead of email.", max_length=64, verbose_name='GNet griddID'),
        ),
    ]
