# Generated by Django 5.2.17 on 2026-09-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_gnet_grid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordocument',
            name='kind',
            field=models.CharField(choices=[('operating_authority', 'DOT operating authority'), ('w9', 'W-9'), ('affiliate_agreement', 'Affiliate agreement'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
