# Generated by Django 5.2.17 on 2026-08-30 01:46

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('leads', '0007_transfer_min_hours_default_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('applies_to', models.CharField(choices=[('driver', 'Driver'), ('vehicle', 'Vehicle')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('applies_to'), name='uniq_renewal_type_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=60)),
                ('model_name', models.CharField(blank=True, max_length=60, verbose_name='Model')),
                ('color', models.CharField(blank=True, max_length=40)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='VIN')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='leads.vehicletype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField()),
                ('document', models.FileField(blank=True, upload_to='renewals/')),
                ('notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='fleet.driver')),
                ('renewal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='fleet.renewaltype')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-expires_on'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('driver__isnull', False), ('vehicle__isnull', True)), models.Q(('driver__isnull', True), ('vehicle__isnull', False)), _connector='OR'), name='renewal_one_subject')],
            },
        ),
    ]
