# Generated by Django 5.2.17 on 2026-08-30 03:39

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_seed_renewal_types'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='renewaltype',
            name='uniq_renewal_type_name_ci',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('applies_to'), name='uniq_renewal_type_name_ci', violation_error_message='A renewal type with that name already exists for that subject.'),
        ),
    ]
