# Generated by Django 5.2.17 on 2026-09-27 16:34

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_renewal_type_violation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='hourly_rate',
            field=apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
