# Generated by Django 5.2.17 on 2026-09-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('balance_failed', 'Balance charge failed'), ('balance_paid', 'Balance paid'), ('deposit_paid', 'Deposit received'), ('sync_failed', 'Sync failed'), ('new_lead', 'New lead'), ('la_changed', 'Update LimoAnywhere'), ('quote_expired', 'Quote expired'), ('dispatch_exception', 'Dispatch exception')], max_length=20),
        ),
    ]
