# Generated by Django 5.2.17 on 2026-09-27 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_customer_feedback'),
        ('notifications', '0006_alter_notification_kind'),
        ('vendors', '0006_vendordocument_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='leads.lead'),
        ),
    ]
